### ISSUE TITLE
 No length map is found. Please set `-F`.

### ISSUE THREAD

**Issue by alisonomica** [milkschen/leviosam2#47] opened 2023-04-18 22:46 UTC
Hello everyone, I am trying to create the index of the chain file but I am getting the following error: "[E::serialize_run] No length map is found. Please set -F.". The command I am using is docker run naechyun/leviosam2 leviosam2 index -c chm13v2-hg38.over.chain -p chm13v2-hg38 -F Homo_sapiens_GRCh38.p14.fasta.fai. I obtained the .fai file by using samtools faidx on my .fasta file downloaded from NCBI and previously modifying the chromosome names to chr1, chr2, etc to match the chain file. Both files are in the folder where I am running the command. I have also tried running "-F .", "-F /root/Resources/GRCh38/fasta/Homo_sapiens_GRCh38.p14.fasta.fai" and "./Homo_sapiens_GRCh38.p14.fasta.fai". Thank you in advance for your help.

<img width="632" alt="Captura de Pantalla 2023-04-18 a la(s) 16 38 23" src="https://user-images.githubusercontent.com/126112273/232920266-38e1b7b1-56c5-4c60-8f32-557ac85fecc1.png">
<img width="908" alt="Captura de Pantalla 2023-04-18 a la(s) 16 39 05" src="https://user-images.githubusercontent.com/126112273/232920365-6fca01e2-594b-4286-9fef-ae6945d4f492.png">
<img width="1161" alt="Captura de Pantalla 2023-04-18 a la(s) 16 40 13" src="https://user-images.githubusercontent.com/126112273/232920520-1fda7b0c-4775-41ab-a32b-e95689b8dea1.png">

**Comment by milkschen** [comment] 2023-04-19 03:24
Hi @alisonomica ,

I tried the following command but could not reproduce your issue. I tried v0.3.0 and v0.2.2.

```
wget https://genome-idx.s3.amazonaws.com/lev/chm13v2-grch38.tar.gz
tar xfzv chm13v2-grch38.tar.gz

wget https://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/p14/hg38.p14.fa.gz
gunzip hg38.p14.fa.gz

leviosam2 index -c chm13v2-grch38/chm13v2-grch38.chain -F hg38.p14.fa.fai -p test
```

Could you take a look at the command above and check if that work for you?

**Comment by milkschen** [comment] 2023-07-06 17:11
Close this issue for now. Please let me know if more discussion/help is needed.

**Closed by milkschen** 2023-07-06 17:11 UTC
