### ISSUE TITLE
Alignment errors after Leviosam2?

### ISSUE THREAD

**Issue by kokyriakidis** [milkschen/leviosam2#13] opened 2022-06-11 07:48 UTC
After Leviosam2 (chm13v2 to hg19) I get the following error in the post-processing steps (Picard ReorderSam)

```
Exception in thread "main" htsjdk.samtools.SAMFormatException: SAM validation error: ERROR::INVALID_ALIGNMENT_START:Record 353, Read name A00371:69:HG73LDMXX:1:1161:16966:28808, Mate Alignment start (176517898) must be <= reference sequence length (171115067) on reference chr6

```
These are the reads from the final chm13-to-hg19 BAM:
```
A00371:69:HG73LDMXX:1:1161:16966:28808	65	chr1	544	60	151M	chr6	176517898	0	CCCGAACCAACCAAACCCCAAAGACACCCCCCACAGTTTATGTAGCTTACCTCCTCAAAGCAATACACTGAAAATGTTTAGACGGGCTCACATCACCCCATAAACAAATAGGTTTGGTCCTAGCCTTTCTATTAGCTCTTAGTAAGATTAC	FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF,:FFFFFFF,F,FFFF:FFFF:FFFFFFFFFFFFFFFFFFFF:FFFFFFF:FFFFFFFFFFF:F,FFFFFFFFFF,FFFFFFFFFFFF:,FF,:FFFFFFF::FFF::FFFFFF	NM:i:0	MD:Z:151	MC:Z:151M	AS:i:151	XS:i:77RF:Z:target

A00371:69:HG73LDMXX:1:1161:16966:28808	129	chr6	176517898	60	151M	chr1	544	0	GGAACACACGGTCATTCTAGGGGCCTTCCCCTGCCCTCCAGCACCCTACTGGACACACCCCCAGCGCATGGAGAAGAAACTGCATGCAGTACCTGCGGGGAACACCGTCAAGTTCCGCTGTCCAGCTGCAGGCAACCCCACGCCCACCATC	:F:FF,FFFFFFF:FFFFFFFF:FFFFFFF:FFFFFFF:::FFFFFF,FFFFFFFFFFFFFFFFFFFFFFFF:FF:FFFFFFFFFFFF:FFFFFFFFFFFFFFFF:FFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	NM:i:0	MD:Z:151	MC:Z:151M	AS:i:151	XS:i:20RF:Z:target
```
**The start position of the second read is larger than the chr6 length.**

These are the reads from the original mapping to chm13v2 BAM:
```
A00371:69:HG73LDMXX:1:1161:16966:28808	129	chr5	177634105	60	151M	chrM	1	0	GGAACACACGGTCATTCTAGGGGCCTTCCCCTGCCCTCCAGCACCCTACTGGACACACCCCCAGCGCATGGAGAAGAAACTGCATGCAGTACCTGCGGGGAACACCGTCAAGTTCCGCTGTCCAGCTGCAGGCAACCCCACGCCCACCATC	:F:FF,FFFFFFF:FFFFFFFF:FFFFFFF:FFFFFFF:::FFFFFF,FFFFFFFFFFFFFFFFFFFFFFFF:FF:FFFFFFFFFFFF:FFFFFFFFFFFFFFFF:FFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	NM:i:0	MD:Z:151	MC:Z:35S116M	AS:i:151	XS:i:20RG:Z:SAMPLE

A00371:69:HG73LDMXX:1:1161:16966:28808	65	chrM	1	58	35S116Mchr5	177634105	0	CCCGAACCAACCAAACCCCAAAGACACCCCCCACAGTTTATGTAGCTTACCTCCTCAAAGCAATACACTGAAAATGTTTAGACGGGCTCACATCACCCCATAAACAAATAGGTTTGGTCCTAGCCTTTCTATTAGCTCTTAGTAAGATTAC	FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF,:FFFFFFF,F,FFFF:FFFF:FFFFFFFFFFFFFFFFFFFF:FFFFFFF:FFFFFFFFFFF:F,FFFFFFFFFF,FFFFFFFFFFFF:,FF,:FFFFFFF::FFF::FFFFFF	NM:i:0	MD:Z:116	MC:Z:151M	AS:i:116	XS:i:92RG:Z:SAMPLE	SA:Z:chrM,16535,+,35M116S,58,0;

A00371:69:HG73LDMXX:1:1161:16966:28808	2113	chrM	16535	58	35M116Hchr5	177634105	0	CCCGAACCAACCAAACCCCAAAGACACCCCCCACA	FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	NM:i:0	MD:Z:35	MC:Z:151M	AS:i:35	XS:i:0	RG:Z:SAMPLE	SA:Z:chrM,1,+,35S116M,58,0;

```
Mapping to hg19 directly with dragmap gave those results:
````
A00371:69:HG73LDMXX:1:1161:16966:28808	65	chrM	544	60	151M	chr5	176517898	0	CCCGAACCAACCAAACCCCAAAGACACCCCCCACAGTTTATGTAGCTTACCTCCTCAAAGCAATACACTGAAAATGTTTAGACGGGCTCACATCACCCCATAAACAAATAGGTTTGGTCCTAGCCTTTCTATTAGCTCTTAGTAAGATTAC	FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF,:FFFFFFF,F,FFFF:FFFF:FFFFFFFFFFFFFFFFFFFF:FFFFFFF:FFFFFFFFFFF:F,FFFFFFFFFF,FFFFFFFFFFFF:,FF,:FFFFFFF::FFF::FFFFFF	RG:Z:1	AS:i:151	XS:i:111	NM:i:0	XQ:i:115

A00371:69:HG73LDMXX:1:1161:16966:28808	129	chr5	176517898	60	151M	chrM	544	0	GGAACACACGGTCATTCTAGGGGCCTTCCCCTGCCCTCCAGCACCCTACTGGACACACCCCCAGCGCATGGAGAAGAAACTGCATGCAGTACCTGCGGGGAACACCGTCAAGTTCCGCTGTCCAGCTGCAGGCAACCCCACGCCCACCATC	:F:FF,FFFFFFF:FFFFFFFF:FFFFFFF:FFFFFFF:::FFFFFF,FFFFFFFFFFFFFFFFFFFFFFFF:FF:FFFFFFFFFFFF:FFFFFFFFFFFFFFFF:FFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	RG:Z:1	AS:i:151	NM:i:0	XQ:i:250
````
**So I guess the first alignment with BWA to chm13v2 was correct (aligning to chr5 and chrM). Leviosam2 somehow translated them to (chr1 and chr6???) in hg19. The alignment position on chr5 is suprisingly the same as the position on chr6 making me wonder if leviosam wanted to write chr5 and somehow wrote chr6. The same applies for chr1 and chrM (!!!)**

The command I used to generate the BAM files is the following:
```
bwa mem -t 15 \
-R "@RG\tID:SAMPLE\tPL:illumina\tPU:SAMPLE\tSM:SAMPLE" -v 1 \
/media/kokyriakidis/PRODUCTION/reference/chm13v2/bwa/chm13v2 \
/media/kokyriakidis/PRODUCTION/input_trimmed/SAMPLE_R1.fastq.gz \
/media/kokyriakidis/PRODUCTION/input_trimmed/SAMPLE_R3.fastq.gz \
| samtools sort -@ 15 -m 4G -O bam \
-o /media/kokyriakidis/PRODUCTION/output/chm13v2/1_Mapping_BWA/SAMPLE-sort.bam -

bash /media/kokyriakidis/PRODUCTION/leviosam2/workflow/leviosam2.sh \
    -a bwamem -A 100 -q 30 -H 5 \
    -i /media/kokyriakidis/PRODUCTION/output/chm13v2/1_Mapping_BWA/SAMPLE-sort.bam \
    -o /media/kokyriakidis/PRODUCTION/output/chm13v2/2_chm13v2_to_hg19/SAMPLE_chm13v2_hg19 \
    -f /media/kokyriakidis/PRODUCTION/reference/hg19/hg19.fa \
    -b /media/kokyriakidis/PRODUCTION/reference/hg19/bwa/hg19.fa \
    -C /media/kokyriakidis/PRODUCTION/chm13v2-hg19/chm13v2-hg19.clft \
    -D /media/kokyriakidis/PRODUCTION/chm13v2-hg19/chm13v2-hg19-lt0.98-map_reduction_k100_e0.01.bed \
    -R /media/kokyriakidis/PRODUCTION/chm13v2-hg19/chm13v2-hg19-source-unliftable-s_5000-winnowmap2-exc_1.bed \
    -t 18

```

I also get some errors from ABRA2 that I do not understand 

```
java.lang.ArrayIndexOutOfBoundsException: 19525
```

Do you have any clue? How do I solve these issues?

**Comment by kokyriakidis** [comment] 2022-06-12 10:52
I also see many wrongly mapped reads vs directly mapping to hg19.

The top row is dragmap+hg19+ABRA2.
The second row is dragmap+hg19.
The third row is BWA-MEM+chm13v2+Leviosam2(BWA-MEM)

![image](https://user-images.githubusercontent.com/33731293/173229629-ef93c85e-6c66-4cd7-b6c8-6d6f520356df.png)

**Comment by milkschen** [comment] 2022-06-12 21:39
Thank you for providing these examples! Your "off-by-one-chromosome" hypothesis for the `A00371:69:HG73LDMXX:1:1161:16966:28808` read sounds reasonable to me. I'll start looking into the issue from that.

And if possible, could you also give me the SAM records for some of the reads you showed using IGV?

**Comment by kokyriakidis** [comment] 2022-06-12 22:38
@milkschen You can have the whole BAM files.

https://drive.google.com/drive/folders/17GI9Z0UnhQITmTUqf9OSGQ8IDgzH6hFn?usp=sharing

**Comment by milkschen** [comment] 2022-07-19 21:23
Hi @kokyriakidis,

Sorry for late reply. I checked the files you uploaded but couldn't reproduce the error that you posted.

I extracted the `A00371:69:HG73LDMXX:1:1161:16966:28808` reads in `issue13.sam`:

```
@HD	VN:1.6	SO:coordinate
@SQ	SN:chr1	LN:248387328
@SQ	SN:chr2	LN:242696752
@SQ	SN:chr3	LN:201105948
@SQ	SN:chr4	LN:193574945
@SQ	SN:chr5	LN:182045439
@SQ	SN:chr6	LN:172126628
@SQ	SN:chr7	LN:160567428
@SQ	SN:chr8	LN:146259331
@SQ	SN:chr9	LN:150617247
@SQ	SN:chr10	LN:134758134
@SQ	SN:chr11	LN:135127769
@SQ	SN:chr12	LN:133324548
@SQ	SN:chr13	LN:113566686
@SQ	SN:chr14	LN:101161492
@SQ	SN:chr15	LN:99753195
@SQ	SN:chr16	LN:96330374
@SQ	SN:chr17	LN:84276897
@SQ	SN:chr18	LN:80542538
@SQ	SN:chr19	LN:61707364
@SQ	SN:chr20	LN:66210255
@SQ	SN:chr21	LN:45090682
@SQ	SN:chr22	LN:51324926
@SQ	SN:chrX	LN:154259566
@SQ	SN:chrY	LN:62460029
@SQ	SN:chrM	LN:16569
@RG	ID:PanelA_LAB1_LIB1	PL:illumina	PU:PanelA_LAB1_LIB1	SM:PanelA_LAB1_LIB1
@PG	ID:bwa	PN:bwa	VN:0.7.17-r1188	CL:bwa mem -t 15 -R @RG\tID:PanelA_LAB1_LIB1\tPL:illumina\tPU:PanelA_LAB1_LIB1\tSM:PanelA_LAB1_LIB1 -v 1 /media/kokyriakidis/PRODUCTION/PFDA_INDELS/reference/chm13v2/bwa/chm13v2 /media/kokyriakidis/PRODUCTION/PFDA_INDELS/input_trimmed/PanelA_LAB1_LIB1_R1.fastq.gz /media/kokyriakidis/PRODUCTION/PFDA_INDELS/input_trimmed/PanelA_LAB1_LIB1_R3.fastq.gz
@PG	ID:samtools	PN:samtools	PP:bwa	VN:1.13	CL:samtools sort -@ 15 -m 4G -O bam -o /media/kokyriakidis/PRODUCTION/PFDA_INDELS/output/chm13v2/1_Mapping_BWA/PanelA_LAB1_LIB1-sort.bam -
A00371:69:HG73LDMXX:1:1161:16966:28808	65	chrM	1	58	35S116M	chr5	177634105	0	CCCGAACCAACCAAACCCCAAAGACACCCCCCACAGTTTATGTAGCTTACCTCCTCAAAGCAATACACTGAAAATGTTTAGACGGGCTCACATCACCCCATAAACAAATAGGTTTGGTCCTAGCCTTTCTATTAGCTCTTAGTAAGATTAC	FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF,:FFFFFFF,F,FFFF:FFFF:FFFFFFFFFFFFFFFFFFFF:FFFFFFF:FFFFFFFFFFF:F,FFFFFFFFFF,FFFFFFFFFFFF:,FF,:FFFFFFF::FFF::FFFFFF	NM:i:0	MD:Z:116	MC:Z:151M	AS:i:116	XS:i:92	RG:Z:PanelA_LAB1_LIB1	SA:Z:chrM,16535,+,35M116S,58,0;
A00371:69:HG73LDMXX:1:1161:16966:28808	2113	chrM	16535	58	35M116H	chr5	177634105	0	CCCGAACCAACCAAACCCCAAAGACACCCCCCACA	FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	NM:i:0	MD:Z:35	MC:Z:151M	AS:i:35	XS:i:0	RG:Z:PanelA_LAB1_LIB1	SA:Z:chrM,1,+,35S116M,58,0;
A00371:69:HG73LDMXX:1:1161:16966:28808	129	chr5	177634105	60	151M	chrM	1	0	GGAACACACGGTCATTCTAGGGGCCTTCCCCTGCCCTCCAGCACCCTACTGGACACACCCCCAGCGCATGGAGAAGAAACTGCATGCAGTACCTGCGGGGAACACCGTCAAGTTCCGCTGTCCAGCTGCAGGCAACCCCACGCCCACCATC	:F:FF,FFFFFFF:FFFFFFFF:FFFFFFF:FFFFFFF:::FFFFFF,FFFFFFFFFFFFFFFFFFFFFFFF:FF:FFFFFFFFFFFF:FFFFFFFFFFFFFFFF:FFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	NM:i:0	MD:Z:151	MC:Z:35S116M	AS:i:151	XS:i:20	RG:Z:PanelA_LAB1_LIB1
```

My chain file was from :

```
wget https://genome-idx.s3.amazonaws.com/lev/chm13v2-hg19.tar.gz
```

My hg19 file was from UCSC:

```
wget https://hgdownload.soe.ucsc.edu/goldenPath/hg19/bigZips/hg19.fa.gz
```

I built the leviosam2 index and run leviosam2 using the following commands
```
leviosam2 index -c chm13v2-hg19/chm13v2-hg19.chain -F hg19.fa.fai -p chm13v2-hg19/chm13v2-hg19
leviosam2 lift -C chm13v2-hg19/chm13v2-hg19.clft -a issue13.sam
```

The lifted results:

```
A00371:69:HG73LDMXX:1:1161:16966:28808	77	*	0	58	35S116M	*	0	0	CCCGAACCAACCAAACCCCAAAGACACCCCCCACAGTTTATGTAGCTTACCTCCTCAAAGCAATACACTGAAAATGTTTAGACGGGCTCACATCACCCCATAAACAAATAGGTTTGGTCCTAGCCTTTCTATTAGCTCTTAGTAAGATTAC	FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF,:FFFFFFF,F,FFFF:FFFF:FFFFFFFFFFFFFFFFFFFF:FFFFFFF:FFFFFFFFFFF:F,FFFFFFFFFF,FFFFFFFFFFFF:,FF,:FFFFFFF::FFF::FFFFFF	MC:Z:151M	AS:i:116	XS:i:92	RG:Z:PanelA_LAB1_LIB1	SA:Z:chrM,16535,+,35M116S,58,0;	LO:Z:UM_UM
A00371:69:HG73LDMXX:1:1161:16966:28808	2113	chrM	544	58	35M116H	chr5	176517898	0	CCCGAACCAACCAAACCCCAAAGACACCCCCCACA	FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	MC:Z:151M	AS:i:35	XS:i:0	RG:Z:PanelA_LAB1_LIB1	SA:Z:chrM,1,+,35S116M,58,0;	LO:Z:L_L
A00371:69:HG73LDMXX:1:1161:16966:28808	137	chr5	176517898	60	151M	=	176517898	0	GGAACACACGGTCATTCTAGGGGCCTTCCCCTGCCCTCCAGCACCCTACTGGACACACCCCCAGCGCATGGAGAAGAAACTGCATGCAGTACCTGCGGGGAACACCGTCAAGTTCCGCTGTCCAGCTGCAGGCAACCCCACGCCCACCATC	:F:FF,FFFFFFF:FFFFFFFF:FFFFFFF:FFFFFFF:::FFFFFF,FFFFFFFFFFFFFFFFFFFFFFFF:FF:FFFFFFFFFFFF:FFFFFFFFFFFFFFFF:FFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	MC:Z:35S116M	AS:i:151	XS:i:20	RG:Z:PanelA_LAB1_LIB1LO:Z:L_UM
```

The positions and contigs were concordant with your dragmap results.

Could you try to re-build a leviosam2 index and see if that works?

**Comment by milkschen** [comment] 2022-08-02 04:05
Let me close the issue for now. Please let me know if you still encounter issues. Happy to look into them!

**Closed by milkschen** 2022-08-02 04:05 UTC
